### PR TITLE
WIP add recipe for sinatra::reloader

### PR DESCRIPTION
**Pull request by ashleygwilliams**
@zzak asked for a Rack::Reloader recipe in #44 

this isn't that, but:
1) it's worthwhile to have this alongside the shotgun recipe, since that doesn't work for Windows.
2) what's the motivation behind a rack::reloader recipe, exactly?

this is a bit of a rewrite of http://www.sinatrarb.com/contrib/reloader.html which i think is a lil confusing (don't weave classic + modular app implementations, just present each individually, IMO)

i'm also going to write up a recipe for rerun. do we think that reloader, shotgun, and rerun should all be one article on reloaders? 3 makes a category, right, heh?

### CODE REVIEW

**Comment by kgrz** [comment]
Ashley mentioned that I can merge these PRs if they are okay. Will merge this since this looks like a good starting point for reloaders.

**Comment by zzak** [comment]
@kgrz In retrospect, I don't think this is enough to warrant a recipe.

If any of this information is missing from the sinatra-contrib documentation, that would be the appropriate place. IMO.

**Comment by kgrz** [comment]
hmm, okay. reverting this merge then

**Comment by zzak** [comment]
@kgrz Yeah, as long as we plan to support reloader, we should do our best to give the first-class docs our love <3

**Pull request merged**
