### PR TITLE
Fix selected item in select

### PR DESCRIPTION
**Pull request by piton4eg**

### CODE REVIEW

**Comment by kgrz** [comment]
Hmm, it seems Chosen (the plugin for handling the dropdown) handles setting the `selected` attribute for us. Can you please explain what this PR does and when it's applicable?

**Comment by piton4eg** [comment]
When you select one of item then Chosen updates page but resets selected item in select element. This PR fix it

**Comment by piton4eg** [comment]
@kgrz rebased

**Comment by kgrz** [comment]
On which browser are you seeing this issue? I checked on Safari—master branch—and it works fine.

**Comment by piton4eg** [comment]
I checked on Chrome, Safari, it looks the same. 
I recorded video for showing what's wrong: 1st - http://recipes.sinatrarb.com/, 2nd - my local branch with fix: http://screencast.com/t/kHk2u9RU

**Comment by kgrz** [comment]
Thanks for the patience to explain this. Merging this.

**Pull request merged**
